#!/bin/bash

# dir of this script
SOURCE="${BASH_SOURCE[0]}"
BASEDIR="$( dirname "$SOURCE" )"

while [ -h "$SOURCE" ]
do
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
    BASEDIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done

BASEDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

. "$BASEDIR/devhelper-common"

remoteName="$1"
if [ -z "$remoteName" ]
then
    remoteName=`remote`
fi

gitUrl=$(git remote show -n $remoteName | grep "Push  URL:" | cut -d ":" -f 2- | tr -d '[[:space:]]' )

if ! (echo "$gitUrl" | grep -q 'git@github.com')
then
    echo >&2 "URL does not point to github: '$gitUrl'"
    exit 1
fi

# git@github.com:sonatype/nexus-enterprise.git
# https://github.com/sonatype/nexus-enterprise/pull/new/$branch
url=$(echo "$gitUrl" | sed -e "s#git@github.com:\(.*\)\.git#https://github.com/\1/pull/new/`current_branch`#")

$BROWSER "$url" 
