#!/bin/bash

# dir of this script
SOURCE="${BASH_SOURCE[0]}"
BASEDIR="$( dirname "$SOURCE" )"

while [ -h "$SOURCE" ]
do
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
    BASEDIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done

BASEDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

. "$BASEDIR/devhelper-common"

branch_name=`current_branch`

tmp=`tmpfile`

git branch -a --merged $REMOTE/$branch_name | grep -v "* $branch_name" | grep -v "$REMOTE/$branch_name" >"$tmp"

if [ "$1" = "--plain" ]
then
    sed -e "s@remotes/$REMOTE/@@" "$tmp"
else
    ( echo "AUTHOR	BRANCH	LAST COMMIT"
    while read branch
    do
	git log -1 --format="%an	`echo $branch | sed -e 's@remotes/@@'`	%ar" "$branch" | head -n 1
    done <"$tmp" | sort ) | column -t -s '	'
fi
