#!/bin/sh

. devhelper-common

git branch -a --merged $REMOTE/master | grep -v master >"$tmp"

( echo "AUTHOR	BRANCH	LAST COMMIT"
while read branch
do
    git l -1 --format="%an	`echo $branch | sed -e 's@remotes/@@'`	%ar" "$branch" | head -n 1
done <"$tmp" | sort ) | column -t -s '	'
