#!/bin/bash

job=$1
number=$2
if [ -z "$number" ] 
then
    # assume $1 is already '$job/$nr'
    dir="$job"
else
    dir="$job/$number"
fi

basedir="$HOME/sonatype/ci/it-logs"


for jdk in java-6x # java-5x
do
    for label in linux win
    do
	tag="jdk=$jdk,label=$label"
	tagdir="$basedir/$dir/$tag"
	baseurl="https://builds.sonatype.org/job/$dir/$tag"
	url=
	echo "Fetching logs for $tag..."
	mkdir -p "$basedir/$dir/$tag" && \
	    curl -s -S -f -n "$baseurl/consoleText" \
		 -o "$tagdir/console.txt" && \
	    curl -s -S -f -n "$baseurl/artifact/*zip*/target.zip" \
		 -o "$tagdir/target.zip" && unzip -q -o "$tagdir/target.zip" -d "$tagdir" && \
	realpath "$tagdir"
    done
done
