#!/bin/bash

set -e

# dir of this script
SOURCE="${BASH_SOURCE[0]}"
BASEDIR="$( dirname "$SOURCE" )"

while [ -h "$SOURCE" ]
do
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
    BASEDIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done


BASEDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"


name="$1"
shift

export BASEDIR

if [ -x $DIR/nx-$name ]
then
    exec /bin/bash $EXEC_OPTS $DIR/nx-$name "$@"
else
    exec /bin/bash $EXEC_OPTS nx-$name "$@"
fi
