#!/bin/bash

set -e

. `dirname $0`/devhelper-common

g=com.sonatype.nexus
a=nexus-professional
v=${1-LATEST}
r=${REPO-public}
if [[ ${v} == *:* ]]
then
    v=`echo $v | sed -e "s/:/ /g"`
read g a v <<EOF
$v
EOF
fi


# get the resolved location of the LATEST artifact
function getLatestLocation(){
  local latest_url=$1
  local redir_url=`curl "$latest_url" --max-redirs 0 --netrc-optional -o /dev/null -w '%{redirect_url}' -s -S`
  echo $redir_url  
}

# get the artifact file name from the url
function parseFileName(){
  local url=$1
  echo ${url##*/}
}


# $tmp is handled by devhelper-common

if [ "$USE_GAV_DIR" = "true" ]
then
  dir="$g.$a-$v-remote"
  mkdir -p "$dir"
  opts="-d $dir"
fi

bundle_url="$NEXUS/service/local/artifact/maven/redirect?r=$r&g=$g&a=$a&c=bundle&e=zip&v=$v"

if [[ "$v" == "LATEST" && "$USE_FILE_DIR" == "true" ]];
then
  bundle_url=$(getLatestLocation "$bundle_url")
  file=$(parseFileName $bundle_url)
  dir=${file%.*}
  if [ -d $dir ]; then
    echo "You already have the LATEST in this directory: $dir"
    exit 1
  fi
  mkdir -p "$dir"
  opts="-d $dir"
fi


echo "Downloading bundle..."
if curl -# "$bundle_url" -f --netrc-optional -L -o "$tmp" 
then
    echo "Extracting bundle..."
    unzip -q -o "$tmp" $opts

    if [ "$TWEAK_ON_GET" == "true" ]
    then
	echo "Tweaking bundle..."
	nx-tweak $dir/$a*
    fi

    if [ "$START_ON_GET" == "true" ]
    then
	echo "Starting bundle..."
	exec nx-run $dir/$a*
    fi

    exit
fi

echo "Downloading jar file..."
# fall back to default main artifact
if curl -# "$NEXUS/service/local/artifact/maven/redirect?r=$r&g=$g&a=$a&e=jar&v=$v" -f --netrc-optional -L -o "$tmp"
then
    mv "$tmp" "$dir/$a-$v.jar"
    exit
fi

echo >&2 "Could not find GAV $g:$a:$v"
exit 1
