#!/bin/bash

. `dirname $0`/devhelper-common

version=${1-LATEST}

curl "$NEXUS/service/local/artifact/maven/redirect?r=public&g=com.sonatype.nexus&a=nexus-professional&c=bundle&e=tar.gz&v=$version" -L | tar xz
