#!/bin/bash

set -e

. $BASEDIR/devhelper-common

r=${REPO-public}

PWD=`pwd`

if [ "$#" -eq 0 ]
then
    cat >&2 <<EOF
USAGE: nx install (FILE|G:A[:V]) [$TARGET_DIR]

This will unpack the given Nexus plugin. 
If a GAV is specified, the plugin bundle will be downloaded first.
If TARGET_DIR is not specified, it will try to use ./nexus/WEB-INF/plugin-repository or unpack into the current directory.
If TARGET_DIR is specified, it will try to use \$TARGET_DIR/nexus/WEB-INF/plugin-repository or unpack into the given directory.

EOF
    exit
elif [ "$#" -eq 2 ]
then
    PWD="$2"
fi

PREPO="$PWD/nexus/WEB-INF/plugin-repository"

if [ -f "$1" ]
then
    tmp="$1"
else
    tmp=`tmpfile`

    gav=`echo $1 | sed -e "s/:/ /g"`
    read g a v <<EOF
$gav
EOF

    if [ -z "$v" ]
    then
	v=LATEST
    fi

    bundle_url="$NEXUS/service/local/artifact/maven/redirect?r=$r&g=$g&a=$a&c=bundle&e=zip&v=$v"
    echo "Downloading plugin..."
    if ! curl -# "$bundle_url" -f --netrc-optional -L -o "$tmp" 
    then
	echo >&2 "Unable to download from $bundle_url"
	exit 1
    fi
fi


if [ -e "$PREPO" ]
then
    if [ -z "$a" ]
    then
	# file was given - strip version from filename and remove old plugins
	a=`basename ${tmp%%-[0-9]*}`
    fi

    if [ `ls -d "$PREPO/$a"* | wc -l` -gt 1 ]
    then
	echo >&2 "Not removing old plugin: multiple matches for prefix '$a':"
	ls >&2 -d "$PREPO/$a"*
    else
	echo "Removing old plugin: $(basename `ls -d "$PREPO/$a"*`)"
	rm -rf "$PREPO/$a"*
    fi

    echo "Extracting plugin..."
    unzip -q -o "$tmp" -d "$PREPO"
else
    unzip -q -o "$tmp"
fi
