#!/bin/bash

### Run Nexus.
### nx-run $nexusDir $execParams
### $execParams are the parameters used to call the Nexus start script. They default to 'console'.

# for old nexus bundles without all-in-one start script
ARCH=linux-x86-32

. $BASEDIR/devhelper-common

function nexus() {
    p="$1" 
    shift

    (
	cd $p
	if [ -x bin/nexus ]
	then
	    echo "running $p/bin/nexus $@"
	    ./bin/nexus "$@"
	elif [ -x bin/jsw/$ARCH/nexus ]
	then
	    echo "running $p/bin/jsw/$ARCH/nexus $@"
	    ./bin/jsw/$ARCH/nexus "$@"
	else
	    while read lsEntry
	    do
		if [ -d "$lsEntry" ] && [[ "$lsEntry" = nexus-* ]]
		then
		    nexusDir="$lsEntry"
		    break
		fi
	    done < <(ls)

	    if [ ! -z "$nexusDir" ]
	    then
		nexus "$nexusDir" "$@"
	    fi
	fi
    )
}

path="$1"
nxcmd="$2"

if [ -z "$nxcmd" ]
then
    # if first arg is a path, use that path as nexus basedir and run default (console)
    if [ "$#" -eq 0 ]
    then
	path="."
	nxcmd="console"
    elif [ -d "$path" ]
    then
	nxcmd=console
    else
	nxcmd="$1"
	path="."
    fi
fi

nexus $path $nxcmd
