#!/bin/bash

### Run Nexus.
### nx-run $nexusDir $execParams
### $execParams are the parameters used to call the Nexus start script. They default to 'console'.

# for old nexus bundles without all-in-one start script
ARCH=linux-x86-32

# dir of this script
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# load common
. $DIR/devhelper-common


function nexus() {
    p="$1" 
    shift

    (
	cd $p
	if [ -x bin/nexus ]
	then
	    echo "running $p/bin/nexus $@"
	    ./bin/jsw/$ARCH/nexus "$@"
	elif [ -x bin/jsw/$ARCH/nexus ]
	then
	    echo "running $p/bin/jsw/$ARCH/nexus $@"
	    ./bin/jsw/$ARCH/nexus "$@"
	fi
    )
}

path="$1"
nxcmd="$2"

if [ -z "$nxcmd" ]
then
    nxcmd="$1"
    path="."
fi

if [ -z "$nxcmd" ]
then
    nxcmd="console"
fi

nexus $path $nxcmd
